In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('sales.csv')
data.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,101-17-6199,A,Yangon,Normal,Male,Food and beverages,45.79,7,0.000,336.5565,3/13/2019,19:44:00.0,Credit card,320.53,4.761905,16.0265,7.0
1,101-81-4070,C,Naypyitaw,Member,Female,Health and beauty,62.82,2,6.282,131.9220,1/17/2019,12:36:00.0,Ewallet,125.64,4.761905,6.2820,4.9
2,102-06-2002,C,Naypyitaw,Member,Male,Sports and travel,25.25,5,0.000,132.5625,3/20/2019,17:52:00.0,Cash,126.25,4.761905,6.3125,6.1
3,102-77-2261,C,Naypyitaw,Member,Male,Health and beauty,65.31,7,0.000,480.0285,3/5/2019,18:02:00.0,Credit card,457.17,4.761905,22.8585,4.2
4,105-10-6182,A,Yangon,Member,Male,Fashion accessories,21.48,2,2.148,45.1080,2/27/2019,12:22:00.0,Ewallet,42.96,4.761905,2.1480,6.6
5,105-31-1824,A,Yangon,Member,Male,Sports and travel,69.52,7,24.332,510.9720,2/1/2019,15:10:00.0,Credit card,486.64,4.761905,24.3320,8.5
6,106-35-6779,A,Yangon,Member,Male,Home and lifestyle,44.34,2,0.000,93.1140,3/27/2019,11:26:00.0,Cash,88.68,4.761905,4.4340,5.8
7,109-28-2512,B,Mandalay,Member,Female,Fashion accessories,97.61,6,29.283,614.9430,1/7/2019,15:01:00.0,Ewallet,585.66,4.761905,29.2830,9.9
8,109-86-4363,B,Mandalay,Member,Female,Sports and travel,60.08,7,21.028,441.5880,2/14/2019,11:36:00.0,Credit card,420.56,4.761905,21.0280,4.5
9,110-05-6330,C,Naypyitaw,Normal,Female,Food and beverages,39.43,6,0.000,248.4090,3/25/2019,20:18:00.0,Credit card,236.58,4.761905,11.8290,9.4

In [4]:
    if data.shape[1] != 18:
        print("Please check that the data was loaded properly. Expected 18 columns.")
    else:
        print("Data loaded successfully.")

Please check that the data was loaded properly. Expected 18 columns.